#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App8.Resource", IsApplication=true)]

namespace App8
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::App8.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int pdf_placeholder = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int placeholder = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int addBtn = 2131099650;
			
			// aapt resource value: 0x7f06001d
			public const int amountText = 2131099677;
			
			// aapt resource value: 0x7f060011
			public const int billText = 2131099665;
			
			// aapt resource value: 0x7f060027
			public const int cameraButton = 2131099687;
			
			// aapt resource value: 0x7f06000b
			public const int claimSpinner = 2131099659;
			
			// aapt resource value: 0x7f060015
			public const int fromButton = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int fromText = 2131099668;
			
			// aapt resource value: 0x7f060028
			public const int galleryButton = 2131099688;
			
			// aapt resource value: 0x7f060009
			public const int idText = 2131099657;
			
			// aapt resource value: 0x7f06002a
			public const int imageCanvas = 2131099690;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout1 = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout2 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout3 = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int linearLayout4 = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int linearLayout5 = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int linearLayout6 = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int linearLayout7 = 2131099675;
			
			// aapt resource value: 0x7f060026
			public const int linearLayout8 = 2131099686;
			
			// aapt resource value: 0x7f060007
			public const int loginButton = 2131099655;
			
			// aapt resource value: 0x7f06000e
			public const int mobileText = 2131099662;
			
			// aapt resource value: 0x7f060023
			public const int officialServiceText = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int officialText = 2131099682;
			
			// aapt resource value: 0x7f060006
			public const int passwordText = 2131099654;
			
			// aapt resource value: 0x7f060029
			public const int pdfButton = 2131099689;
			
			// aapt resource value: 0x7f060021
			public const int personalServiceText = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int personalText = 2131099680;
			
			// aapt resource value: 0x7f06002b
			public const int submitButton = 2131099691;
			
			// aapt resource value: 0x7f060000
			public const int text1 = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int textView1 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int textView2 = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int textView3 = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int textView4 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int textView5 = 2131099667;
			
			// aapt resource value: 0x7f060017
			public const int textView6 = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int textView7 = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int textView8 = 2131099676;
			
			// aapt resource value: 0x7f060025
			public const int textView9 = 2131099685;
			
			// aapt resource value: 0x7f060019
			public const int toButton = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int toText = 2131099672;
			
			// aapt resource value: 0x7f060001
			public const int toolbar = 2131099649;
			
			// aapt resource value: 0x7f060024
			public const int totalApprovedText = 2131099684;
			
			// aapt resource value: 0x7f060004
			public const int userText = 2131099652;
			
			// aapt resource value: 0x7f06001f
			public const int valueServiceText = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int valueText = 2131099678;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int spinner_item = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
